version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X github.com/PapaDanielVi/secret-shift/cmd.Version={{ .Tag }}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

brews:
  - repository:
      owner: PapaDanielVi
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    homepage: "https://github.com/PapaDanielVi/secret-shift"
    description: "SecretShift is a CLI tool for migrating and syncing secrets and environment variables between providers"
    license: "MIT"

    test: |
      system "#{bin}/secret-shift --version"
